### ISSUE TITLE
General Updates

### ISSUE THREAD

**Issue by M3CPR0J3CT** [M3CPR0J3CT/MEC#1]
@5CR1PT0GR4M there are many updates available for you now.

**Comment by 5CR1PT0GR4M** [comment]
OK saw that. Cheers. I'll follow the Project too.

**Comment by 5CR1PT0GR4M** [comment]
OK saw that. Cheers. I'll follow the Project too. 👍

**Comment by ghost** [comment]
OK saw that. Cheers. I'll follow the Project too. 👍
