### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ghost** [M3CPR0J3CT/MEC#21]
I believe that 4 is much, much, much more modern!
#FlatDesign!

What is your idea re the signatures? Do you want to derive digital stamps from it?

**Comment by M1NU5** [comment]
I could go with 4. I like the idea of... everyone should have ownership of the quality of the product. For me, when I put my signature on something I am endorsing it as being correct. It makes people think before they put their name on something. So as a minimum, our product should have the signatures of Minus et Cortex. If the team gets bigger then maybe we add other people's signatures to the logo to make them feel part of the project and part of the team/product. 

Thoughts?

**Comment by ghost** [comment]
Signing the actual product [like this](https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Astronaut_signatures_at_SpaceX.jpg/1024px-Astronaut_signatures_at_SpaceX.jpg) at Space X you mean :)

**Comment by M1NU5** [comment]
I could go with 4. I like the idea of... everyone should have ownership of the quality of the product. For me, when I put my signature on something I am endorsing it as being correct. It makes people think before they put their name on something. So as a minimum, our product should have the signatures of Minus et Cortex. If the team gets bigger then maybe we add other people's signatures to the logo to make them feel part of the project and part of the team/product. 

Thoughts?

**Comment by M1NU5** [comment]
Yeah exactly like spacex!

**Comment by ghost** [comment]
[Logo 4](https://github.com/M3CPR0J3CT/MEC/blob/master/Media/MECLogo4White.png) selected:
- Black on White for Documentation and Official Paperwork,
- White on any colour for Hardware Marking or Watermarks on pictures.

**Comment by ghost** [comment]
- [x] Create an alpha .png version (i.e. Transparent Background for the White on Coulor use cases).

**Comment by ghost** [comment]
This is done:
- [Here](https://github.com/M3CPR0J3CT/MEC/blob/master/Media/MECLogo4WhiteTransparent.png),
- And a smaller version (30%) will be available [there](https://github.com/M3CPR0J3CT/MEC/blob/master/Media/MECLogo4WhiteTransparentSmall.png).

@M1NU5 
Closed.

**Comment by M1NU5** [comment]
Looks good to me!! Nice work!
